version: "3.7"
services:

 # PHP Services. Настройка для PHP образа
  app:
    build:
      args: 
        user: appboy
        uid: 1001
      context: ./docker
      dockerfile: Dockerfile
    image: php:7.4-fpm
    container_name: app_mysite
    volumes: 
     - ./src:/var/www/mysite.kz
     - ./docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
     - "9000:9000"
    networks: 
      - lamborghini

  # NGINX Service. Настройка сервера NGINX
  nginx:
    image: nginx:1.19.6-alpine
    container_name: nginx_mysite
    restart: unless-stopped
    tty: true
    ports: 
      - "8080:80"
    depends_on: 
      - app
      - mysql
    volumes: 
      - ./src:/var/www/mysite.kz
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    networks:
     - lamborghini

  # MYSQL Service. Настройка базы данных MYSQL
  mysql:
    image: mysql:5.7.33
    container_name: mysql_mysite
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: appboy_db
      MYSQL_USER: appboy
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./database/mysql:/var/lib/mysql
      - ./docker/mysql/conf.d/my.cnf:/etc/mysql/my.cnf
    networks:
      - lamborghini
  
  #PHPMyadmin Srvice Настройка для Phpmyadmin
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    container_name: phpmyadmin_mysite
    depends_on:
       - mysql
    ports: 
       - "8081:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    networks:
       - lamborghini


networks: 
  lamborghini: